# Generated by Django 5.1.4 on 2025-01-09 23:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('financeapp', '0004_remove_category_category_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='income',
            name='income_frequency',
        ),
    ]
