# Generated by Django 5.1.4 on 2025-01-10 06:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('financeapp', '0005_remove_income_income_frequency'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='income',
            name='description',
        ),
    ]
